### ISSUE TITLE
Szablon projektu graficznego 

### ISSUE THREAD

**Issue by dawidkeller95** [dawidkeller95/Projektzespolowy#11]
Szablon projektu graficznego

**Comment by dawidkeller95** [comment]
![wstepny podglad graficzny aplikacji](https://cloud.githubusercontent.com/assets/25954410/24083383/4146fbce-0cd6-11e7-991b-8e25f5083920.png)

Wstępny wygląd aplikacji youtufy moim zdaniem chciałbym by wyglądał w taki sposób. 
Prosił bym o opinie co i tym sądzicie aby do końca miesiąca powoli zabrać się za jej pisanie :)

![dwa](https://cloud.githubusercontent.com/assets/25954410/24083395/68c77f52-0cd6-11e7-8ad3-81fdf1c0b740.png)

**Comment by SzewskiJanusz** [comment]
Gdzie będzie wyświetlany film?

**Comment by dawidkeller95** [comment]
nad polami C1 ,C2 .
