### ISSUE TITLE
Tworzenie aplikacji

### ISSUE THREAD

**Issue by dawidkeller95** [dawidkeller95/Projektzespolowy#16]
Ten wątek jest odnośnie tworzenia komponentu i budowy aplikacji Youtufy

**Comment by bartkopolak** [comment]
![17440439_1440460189362123_2082133447_n](https://cloud.githubusercontent.com/assets/24453043/24195657/e39b9d8c-0efa-11e7-9fa6-8f6cdc1c7169.png)

**Comment by dawidkeller95** [comment]
![apka](https://cloud.githubusercontent.com/assets/25954410/24699786/6f71a072-19f5-11e7-89ea-dfcdd4079291.PNG)

Tzw "Sucha" aplikacja youtufy. Co prawda ciężko to nazwać aplikacje aplikacją bez funkcjonalności aczkolwiek rozmieszczenie komponentów jest bez zmian . 
Do przyszłego tygodnia dodam funkcjonalność .

**Comment by dawidkeller95** [comment]
uważam że aplikacje zostały stworzone . Wątek zostaje zakończony
