### ISSUE TITLE
Tworzenie aplikacji panelu administratora

### ISSUE THREAD

**Issue by bartkopolak** [dawidkeller95/Projektzespolowy#22]

**Comment by bartkopolak** [comment]
Dodałem prototyp interfejsu

**Comment by bartkopolak** [comment]
+ informacja o zalogowanym użytkowniku po prawej stronie, obok hyperlinku Wyloguj
+ ustawić proporcje kolumn w tabelach
+ zrobić estetycznie wyglądajacy design (Sebastian)
+ skrócić nazwy przycisków
+ zastosować prawidłowe kodowanie

**Comment by dawidkeller95** [comment]
Prace nad panelem sterowania uważam za zakończone .
